-- Recipe App Seed Data
-- Bu dosya seeder/factory yerine kullanılır
-- MySQL veritabanına veri eklemek için kullanın

-- Önce kullanıcı oluştur
INSERT INTO `users` (`name`, `email`, `password`, `email_verified_at`, `created_at`, `updated_at`) VALUES
('Test User', 'test@example.com', '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NOW(), NOW(), NOW()),
('Test Chef', 'chef@example.com', '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NOW(), NOW(), NOW());

-- Recipe Categories (Tarif Kategorileri)
INSERT INTO `recipe_categories` (`name`, `slug`, `description`, `color`, `icon`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES
('Ana Yemek', 'ana-yemek', 'Nefis ana yemek tarifleri', '#ff6b35', 'fas fa-drumstick-bite', 1, 1, NOW(), NOW()),
('Tatlı', 'tatli', 'Lezzetli tatlı tarifleri', '#e83e8c', 'fas fa-birthday-cake', 1, 2, NOW(), NOW()),
('Çorba', 'corba', 'Sıcacık çorba tarifleri', '#17a2b8', 'fas fa-bowl-hot', 1, 3, NOW(), NOW()),
('Salata', 'salata', 'Taze ve sağlıklı salata tarifleri', '#28a745', 'fas fa-leaf', 1, 4, NOW(), NOW()),
('İçecek', 'icecek', 'Serinleten içecek tarifleri', '#20c997', 'fas fa-coffee', 1, 5, NOW(), NOW());

-- Recipes (Tarifler)
-- Not: user_id ve recipe_category_id değerleri, yukarıdaki INSERT'lerden sonra oluşan ID'lere göre ayarlanmalı
-- Bu örnekte user_id=2 (Test Chef), category_id'ler 1-5 arası

INSERT INTO `recipes` (`title`, `slug`, `description`, `instructions`, `ingredients`, `user_id`, `recipe_category_id`, `prep_time`, `cook_time`, `total_time`, `servings`, `difficulty`, `tags`, `chef_notes`, `rating`, `rating_count`, `views`, `is_featured`, `is_published`, `published_at`, `created_at`, `updated_at`) VALUES
('Ev Yapımı Mantarli Spagetti', 'ev-yapimi-mantarli-spagetti', 'Kremsi mantar soslu nefis spagetti tarifi. Evde kolayca yapabileceğiniz restaurant lezzeti.', '<h3>Hazırlık Aşaması</h3><p>Makarnayı kaynar tuzlu suda al dente olana kadar pişirin.</p><h3>Sos Hazırlama</h3><p>Tavada tereyağını eritin, mantarları ekleyin ve kavurun.</p><p>Krema ve baharatları ekleyip karıştırın.</p><h3>Sunum</h3><p>Makarna ile sosu karıştırıp sıcak servis yapın.</p>', JSON_ARRAY('400g spagetti makarna', '300g taze mantar', '200ml krema', '2 diş sarımsak', '1 soğan', '50g tereyağı', 'Tuz, karabiber', 'Rendelenmiş parmesan peyniri'), 2, 1, 15, 25, 40, 4, 'orta', JSON_ARRAY('makarna', 'mantar', 'kremali', 'italyan'), 'Mantarları iyi kavurmak lezzeti artırır.', 4.50, 23, 1250, 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), NOW(), NOW()),

('Çikolatalı Sufle', 'cikolatali-sufle', 'İçi akıkan, dışı çıtır nefis çikolatalı sufle. Misafirlerinizi etkileyecek desert.', '<h3>Sufle Hazırlığı</h3><p>Çikolata ve tereyağını benmari usulü eritin.</p><p>Yumurta sarılarını şekerle çırpın.</p><h3>Pişirme</h3><p>Karışımı kaliplara doldurun.</p><p>220°C fırında 12 dakika pişirin.</p>', JSON_ARRAY('200g bitter çikolata', '100g tereyağı', '4 yumurta', '80g toz şeker', '2 yemek kaşığı un', 'Vanilin', 'Tereyağı (kalip için)'), 2, 2, 20, 12, 32, 6, 'zor', JSON_ARRAY('çikolata', 'sufle', 'desert', 'fırın'), 'Sufleyi hemen servis edin, bekletmeyin.', 4.80, 15, 890, 1, 1, DATE_SUB(NOW(), INTERVAL 8 DAY), NOW(), NOW()),

('Mercimek Çorbası', 'mercimek-corbasi', 'Geleneksel Türk mutfağının vazgeçilmez lezzeti mercimek çorbası.', '<h3>Mercimek Hazırlığı</h3><p>Kırmızı mercimeği yıkayıp süzdürün.</p><h3>Pişirme</h3><p>Sebzelerle birlikte haşlayın.</p><p>Blender\'dan geçirip kreması haline getirin.</p>', JSON_ARRAY('1 su bardağı kırmızı mercimek', '1 orta boy soğan', '1 havuç', '2 yemek kaşığı zeytinyağı', '1 tatlı kaşığı domates salçası', 'Tuz, karabiber', 'Limon'), 2, 3, 10, 30, 40, 4, 'kolay', JSON_ARRAY('mercimek', 'çorba', 'geleneksel', 'sağlıklı'), 'Servis sırasında limon sıkmayı unutmayın.', 4.30, 31, 2180, 0, 1, DATE_SUB(NOW(), INTERVAL 12 DAY), NOW(), NOW()),

('Çoban Salatası', 'coban-salatasi', 'Taze sebzelerle hazırlanan geleneksel çoban salatası. Hafif ve lezzetli.', '<h3>Sebze Hazırlığı</h3><p>Tüm sebzeleri küçük küp şeklinde doğrayın.</p><h3>Karıştırma</h3><p>Büyük bir kasede tüm malzemeleri karıştırın.</p><p>Sos malzemelerini ekleyip karıştırın.</p>', JSON_ARRAY('3 domates', '2 salatalık', '1 yesil biber', '1 kırmızı soğan', '100g beyaz peynir', 'Maydanoz', '3 yemek kaşığı zeytinyağı', '1 yemek kaşığı limon suyu', 'Tuz'), 2, 4, 15, 0, 15, 4, 'kolay', JSON_ARRAY('salata', 'taze', 'geleneksel', 'sağlıklı'), 'Sebzeleri servis öncesinde doğrayın.', 4.10, 18, 743, 0, 1, DATE_SUB(NOW(), INTERVAL 15 DAY), NOW(), NOW()),

('Ev Yapımı Limonata', 'ev-yapimi-limonata', 'Serinleten, taze limonlardan hazırlanan ev yapımı limonata.', '<h3>Şerbet Hazırlığı</h3><p>Şeker ve suyu kaynatıp şerbet yapın.</p><h3>Karıştırma</h3><p>Limon suyunu soğuk şerbete karıştırın.</p><p>Buzla servis yapın.</p>', JSON_ARRAY('6 taze limon', '1 su bardağı şeker', '4 su bardağı su', 'Buz', 'Nane yaprakları (süsleme)'), 2, 5, 10, 5, 15, 4, 'kolay', JSON_ARRAY('limonata', 'serinletici', 'yaz', 'ev yapımı'), 'Limonları sıkmadan önce oda sıcaklığında bekletin.', 4.00, 12, 560, 0, 1, DATE_SUB(NOW(), INTERVAL 18 DAY), NOW(), NOW());

-- Blog Categories (Blog Kategorileri)
INSERT INTO `blog_categories` (`name`, `slug`, `description`, `color`, `icon`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES
('Ekmek & Hamur İşleri', 'ekmek-hamur-isleri', 'Evde ekmek, pasta, börek ve diğer hamur işleri tarifleri', '#ff6b35', 'fas fa-bread-slice', 1, 1, NOW(), NOW()),
('Sağlıklı Beslenme', 'saglikli-beslenme', 'Sağlıklı yaşam için beslenme önerileri ve tarifleri', '#28a745', 'fas fa-leaf', 1, 2, NOW(), NOW()),
('Mutfak İpuçları', 'mutfak-ipuclari', 'Mutfakta işinizi kolaylaştıracak pratik ipuçları', '#17a2b8', 'fas fa-lightbulb', 1, 3, NOW(), NOW()),
('Geleneksel Tatlılar', 'geleneksel-tatlilar', 'Türk mutfağının geleneksel tatlı tarifleri', '#e83e8c', 'fas fa-birthday-cake', 1, 4, NOW(), NOW()),
('Sağlıklı İçecekler', 'saglikli-icecekler', 'Doğal ve sağlıklı içecek tarifleri', '#20c997', 'fas fa-glass-whiskey', 1, 5, NOW(), NOW()),
('Kahvaltı', 'kahvalti', 'Güne enerjik başlamak için kahvaltı tarifleri', '#fd7e14', 'fas fa-coffee', 1, 6, NOW(), NOW());

-- Blog Posts (Blog Yazıları)
-- Not: blog_category_id değerleri, yukarıdaki blog_categories INSERT'lerinden sonra oluşan ID'lere göre ayarlanmalı
-- Bu örnekte category_id'ler 1-6 arası

INSERT INTO `blog_posts` (`title`, `slug`, `excerpt`, `content`, `author_name`, `author_title`, `author_bio`, `blog_category_id`, `tags`, `reading_time`, `views`, `is_featured`, `is_published`, `published_at`, `created_at`, `updated_at`) VALUES
('Ev Yapımı Ekmek Tarifi ve Püf Noktaları', 'ev-yapimi-ekmek-tarifi-puf-noktalari', 'Evde kolayca yapabileceğiniz nefis ekmek tarifi ve başarılı olmanız için önemli püf noktaları. Mutfakta ekmek yapmanın sırlarını keşfedin.', '<h3>Evde Ekmek Yapmanın Temelleri</h3><p>Evde ekmek yapmak sanıldığından çok daha kolay! Doğru malzemeler ve tekniklerle nefis ekmekler yapabilirsiniz.</p><h4>Gerekli Malzemeler:</h4><ul><li>500g un (bread flour tercih edilir)</li><li>300ml ılık su</li><li>7g aktif kuru maya</li><li>1 tatlı kaşığı tuz</li><li>1 yemek kaşığı zeytinyağı</li><li>1 tatlı kaşığı şeker</li></ul><h4>Yapılışı:</h4><ol><li><strong>Maya Aktivasyonu:</strong> Ilık suya şeker ve mayayı karıştırın. 5-10 dakika bekleyerek mayanın köpürmesini sağlayın.</li><li><strong>Hamur Hazırlama:</strong> Büyük bir kaba unu alın, ortasını çukur yapın. Maya karışımını ve zeytinyağını ekleyin.</li><li><strong>Yoğurma:</strong> Tuz dışında her şeyi karıştırın, sonra tuzu ekleyerek 8-10 dakika yoğurun.</li><li><strong>İlk Mayalanma:</strong> Yağlanmış kaba alın, üzerini örtün. 1 saat mayalanmaya bırakın.</li><li><strong>Şekil Verme:</strong> Hamurun havasını alın, istediğiniz şekli verin.</li><li><strong>İkinci Mayalanma:</strong> 30-45 dakika daha mayalayın.</li><li><strong>Pişirme:</strong> 220°C fırında 25-30 dakika pişirin.</li></ol><p>Bu tarif ile evde enfes ekmekler yapabilirsiniz. Sabırla uygulayın ve mutfağınız mis gibi ekmek kokusu ile dolsun!</p>', 'Chef Ayşe', 'Ekmek Ustası', '20 yıllık deneyime sahip ekmek ustası. Geleneksel ekmek yapım tekniklerini modern mutfaklara uyarlamakta uzman.', 1, JSON_ARRAY('ekmek', 'hamur işi', 'ev yapımı', 'temel tarifler'), '8 dakika', 1250, 1, 1, DATE_SUB(NOW(), INTERVAL 6 DAY), NOW(), NOW()),

('Kış Sebzeleri ile Sağlıklı Çorbalar', 'kis-sebzeleri-saglikli-corbalar', 'Kış aylarında vücudunuzu sıcak tutacak ve bağışıklığınızı güçlendirecek nefis çorba tarifleri ve beslenme önerileri.', '<h3>Kış Sebzelerinin Faydaları</h3><p>Kış mevsiminde doğanın bize sunduğu sebzeler, vücudumuzun bu zorlu dönemde ihtiyaç duyduğu vitaminler ve mineraller açısından çok zengindir.</p><h4>Kış Sebzelerinin Besin Değerleri:</h4><ul><li><strong>Havuç:</strong> Beta karoten, A vitamini, lif</li><li><strong>Kabak:</strong> C vitamini, potasyum, lif</li><li><strong>Brokoli:</strong> C vitamini, K vitamini, folat</li><li><strong>Karnabahar:</strong> C vitamini, folat, lif</li><li><strong>Pırasa:</strong> A vitamini, K vitamini, folat</li></ul><h4>3 Nefis Kış Çorbası Tarifi:</h4><h5>1. Balkabağı Çorbası</h5><p><strong>Malzemeler:</strong> 500g balkabağı, 1 soğan, 2 diş sarımsak, 500ml sebze suyu, tuz, karabiber, tarçın</p><p><strong>Yapılışı:</strong> Sebzeleri kavurun, su ekleyip haşlayın, blender\'dan geçirin.</p><h5>2. Brokoli Çorbası</h5><p><strong>Malzemeler:</strong> 1 brokoli, 1 patates, 1 soğan, 600ml tavuk suyu, krema</p><p><strong>Yapılışı:</strong> Sebzeleri haşlayın, püre yapın, krema ekleyin.</p><p>Bu çorbalar hem bağışıklığınızı güçlendirir hem de kış soğuğunda sizi ısıtır!</p>', 'Diyetisyen Mehmet', 'Beslenme Uzmanı', 'Beslenme ve diyet uzmanı. Sağlıklı yaşam için pratik öneriler sunmakta uzman.', 2, JSON_ARRAY('çorba', 'kış sebzeleri', 'sağlıklı beslenme', 'vitamin'), '6 dakika', 892, 0, 1, DATE_SUB(NOW(), INTERVAL 11 DAY), NOW(), NOW()),

('Baklava Yapımının Sırları', 'baklava-yapiminin-sirlari', 'Geleneksel Türk tatlısı baklavanın evde nasıl yapılacağını, yufka açma tekniklerini ve şerbet püf noktalarını öğrenin.', '<h3>Baklava Yapımının Temelleri</h3><p>Baklava yapımı sabır ve teknik gerektirir. İşte en önemli sırlar...</p><h4>Malzemeler:</h4><ul><li>1 paket hazır yufka (veya evde açılmış)</li><li>200g tereyağı</li><li>2 su bardağı ceviz</li><li>1 yemek kaşığı şeker</li><li>1 tatlı kaşığı tarçın</li></ul><h4>Şerbet için:</h4><ul><li>3 su bardağı şeker</li><li>2.5 su bardağı su</li><li>1 yemek kaşığı limon suyu</li></ul><p>Baklava yapımında en önemli nokta, şerbetin soğuk, baklavanın sıcak olmasıdır!</p>', 'Usta Ahmet', 'Tatlı Ustası', 'Geleneksel Türk tatlıları konusunda 30 yıllık deneyime sahip usta.', 4, JSON_ARRAY('baklava', 'geleneksel tatlı', 'yufka', 'şerbet'), '12 dakika', 2180, 1, 1, DATE_SUB(NOW(), INTERVAL 16 DAY), NOW(), NOW()),

('Vitamin C Deposu Meyveli Smoothie Tarifleri', 'vitamin-c-meyveli-smoothie-tarifleri', 'Bağışıklığınızı güçlendirmek için vitamin C açısından zengin, lezzetli ve besleyici smoothie tarifleri.', '<h3>Smoothie\'lerin Faydaları</h3><p>Smoothie\'ler hem pratik hem besleyici. Vitamin C deposu tarifler...</p><h4>3 Nefis Smoothie Tarifi:</h4><h5>1. Portakal-Mango Smoothie</h5><ul><li>1 portakal</li><li>1/2 mango</li><li>1 muz</li><li>1 su bardağı süt</li></ul><h5>2. Çilek-Kivi Smoothie</h5><ul><li>10 çilek</li><li>2 kivi</li><li>1 yemek kaşığı bal</li><li>1/2 su bardağı yoğurt</li></ul><p>Bu smoothie\'ler sabah kahvaltısında veya ara öğünlerde tüketilebilir.</p>', 'Beslenme Uzmanı Zeynep', 'Diyet Uzmanı', 'Sağlıklı beslenme ve detoks programları konusunda uzman diyetisyen.', 5, JSON_ARRAY('smoothie', 'vitamin C', 'meyve', 'sağlıklı içecek'), '5 dakika', 743, 0, 1, DATE_SUB(NOW(), INTERVAL 19 DAY), NOW(), NOW()),

('Kahvaltıda Protein: Yumurtalı Tarifler', 'kahvaltida-protein-yumurtali-tarifler', 'Güne enerjik başlamak için protein açısından zengin, çeşitli yumurtalı kahvaltı tarifleri ve beslenme önerileri.', '<h3>Kahvaltının Önemi</h3><p>Kahvaltı günün en önemli öğünü. Protein ile güçlü başlayın...</p><h4>5 Farklı Yumurta Tarifi:</h4><h5>1. Scrambled Eggs</h5><p>Kremsi ve lezzetli çırpılmış yumurta</p><h5>2. Omlet</h5><p>Sebzeli ve peynirli omlet çeşitleri</p><h5>3. Menemen</h5><p>Geleneksel Türk kahvaltı lezzeti</p><h5>4. Eggs Benedict</h5><p>Şık sunum için mükemmel seçenek</p><h5>5. Yumurtalı Avokado Toast</h5><p>Modern ve sağlıklı alternatif</p>', 'Chef Murat', 'Kahvaltı Uzmanı', 'Kahvaltı kültürü ve protein açısından zengin öğünler konusunda uzman şef.', 6, JSON_ARRAY('kahvaltı', 'yumurta', 'protein', 'sağlıklı beslenme'), '7 dakika', 1055, 0, 1, DATE_SUB(NOW(), INTERVAL 22 DAY), NOW(), NOW()),

('Mutfak Aletleri Nasıl Temizlenir?', 'mutfak-aletleri-nasil-temizlenir', 'Mutfak aletlerinizi doğru şekilde temizleyerek hem hijyeni koruyun hem de ömürlerini uzatın. Pratik temizlik ipuçları.', '<h3>Mutfak Hijyeni</h3><p>Mutfak hijyeni lezzet kadar önemlidir. Doğru temizlik teknikleri...</p><h4>Temel Temizlik Kuralları:</h4><ul><li>Her kullanımdan sonra temizleyin</li><li>Doğru deterjan seçin</li><li>Sıcak su kullanın</li><li>İyice durulayın</li><li>Kurutun ve saklayın</li></ul><h4>Özel Aletler:</h4><h5>Bıçaklar</h5><p>Keskin kenarlı aletlerin özel bakımı</p><h5>Tahta Kesme Tahtaları</h5><p>Bakterilerden korunma yöntemleri</p><h5>Tencere ve Tavalar</h5><p>Farklı malzemeler için farklı yöntemler</p>', 'Ev Hanımı Fatma', 'Temizlik Uzmanı', 'Ev hanımı deneyimleriyle pratik temizlik çözümleri sunan uzman.', 3, JSON_ARRAY('temizlik', 'hijyen', 'mutfak aletleri', 'bakım'), '4 dakika', 654, 0, 1, DATE_SUB(NOW(), INTERVAL 25 DAY), NOW(), NOW());

